CREATE DATABASE IF NOT EXISTS friendTable
DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

USE friendTable;

CREATE TABLE IF NOT EXISTS user(
	id VARCHAR(128) PRIMARY KEY,
	jsonstr VARCHAR(1024)
); 

CREATE TABLE IF NOT EXISTS admin(
	id VARCHAR(128) PRIMARY KEY,
	jsonstr VARCHAR(1024)
);

CREATE TABLE IF NOT EXISTS feed(
	no INT UNSIGNED PRIMARY KEY,
	id VARCHAR(128),
	jsonstr VARCHAR(8192)
);

CREATE TABLE IF NOT EXISTS friend(
	id VARCHAR(128),
	frid VARCHAR(128),
	INDEX idx1(id)
);